elf/crypto_sign_sqisign1d_lvl1_p248_uncompressed_m4_arithmetic_%.elf: CPPFLAGS+=-DRADIX_32 -DARITH_M4 -DBIG_PUBLIC_KEY_TESTS
obj/libcrypto_sign_sqisign1d_lvl1_p248_uncompressed_m4_arithmetic.a: CPPFLAGS+=-DRADIX_32 -DARITH_M4 -DBIG_PUBLIC_KEY_TESTS
