elf/crypto_sign_sqisign1d_lvl1_p248_uncompressed_m4_modarith_codegen_inlinefp2_%.elf: CPPFLAGS+=-DRADIX_32 -DARITH_M4 -DBIG_PUBLIC_KEY_TESTS
obj/libcrypto_sign_sqisign1d_lvl1_p248_uncompressed_m4_modarith_codegen_inlinefp2.a: CPPFLAGS+=-DRADIX_32 -DARITH_M4 -DBIG_PUBLIC_KEY_TESTS
