elf/crypto_sign_sqisign1d_lvl1_p248_smart_fiat_crypto_fastram_%.elf: CPPFLAGS+=-DRADIX_32 -DARITH_REF -DBIG_PUBLIC_KEY_TESTS
obj/libcrypto_sign_sqisign1d_lvl1_p248_smart_fiat_crypto_fastram.a: CPPFLAGS+=-DRADIX_32 -DARITH_REF -DBIG_PUBLIC_KEY_TESTS
