elf/crypto_sign_sqisign1d_lvl1_p248_uncompressed_mikes_arithmetic_fastram_%.elf: CPPFLAGS+=-DRADIX_32 -DARITH_MIKE -DBIG_PUBLIC_KEY_TESTS
obj/libcrypto_sign_sqisign1d_lvl1_p248_uncompressed_mikes_arithmetic_fastram.a: CPPFLAGS+=-DRADIX_32 -DARITH_MIKE -DBIG_PUBLIC_KEY_TESTS
