on:
  push:
    branches:
      - master
  pull_request:
    types: [review_requested]
jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.8.0
        with:
          release: 13.2.Rel1
      - name: Build All (stm32f4discovery)
        run: make PLATFORM=stm32f4discovery -j2
      - name: Build All (nucleo-l476rg)
        run: make PLATFORM=nucleo-l476rg -j2
      - name: Build All (nucleo-l4r5zi)
        run: make PLATFORM=nucleo-l4r5zi -j2
      - name: Build All (cw308t-stm32f3)
        run: make PLATFORM=cw308t-stm32f3 -j2
      - name: Build All (cw308t-stm32f415)
        run: make PLATFORM=cw308t-stm32f415 -j2
      - name: Build All (mps2-an386)
        run: make PLATFORM=mps2-an386 -j2